let a = parseFloat(prompt("Insira uma idade:"))
let b = parseFloat(prompt("Insira uma idade:"))
let c = parseFloat(prompt("Insira uma idade:"))
let d = parseFloat(prompt("Insira uma idade:"))
let e = parseFloat(prompt("Insira uma idade:"))
let f = parseFloat(prompt("Insira uma idade:"))
let g = parseFloat(prompt("Insira uma idade:"))
let h = parseFloat(prompt("Insira uma idade:"))
let i = parseFloat(prompt("Insira uma idade:"))
let j = parseFloat(prompt("Insira uma idade:"))
let k = parseFloat(prompt("Insira uma idade:"))
let l = parseFloat(prompt("Insira uma idade:"))
let m = parseFloat(prompt("Insira uma idade:"))
let n = parseFloat(prompt("Insira uma idade:"))
let o = parseFloat(prompt("Insira uma idade:"))
let p = parseFloat(prompt("Insira uma idade:"))
let q = parseFloat(prompt("Insira uma idade:"))
let r = parseFloat(prompt("Insira uma idade:"))
let s = parseFloat(prompt("Insira uma idade:"))
let t = parseFloat(prompt("Insira uma idade:"))

let media = (a+ +b + c + d+ e+ f+ g + h+ i+ j + k +l +m + n +o +p +q +r +s + t)/20

document.write ("A média das idades é: " + media)